version: '3.7'

services:

  django:
    image: codeforacause/website-horizont-center:backend-#{TAG_NUMBER}#
    container_name: horizont-center-django
    environment:
      - APP_ENV=development
      - DB_NAME=caregivers
      - DB_USERNAME=caregivers
      - DB_PASSWORD=#{DB_PASSWORD}#
      - DB_HOSTNAME=postgres
      - DJANGO_PORT=8000
      - DJANGO_SUPERUSER_EMAIL=#{DJANGO_EMAIL}#
      - DJANGO_SUPERUSER_PASSWORD=#{DJANGO_PASSWORD}#
      - EMAIL_HOST_USER=#{EMAIL_HOST_USER}#
      - EMAIL_HOST_PASSWORD=#{EMAIL_HOST_PASSWORD}#
    ports:
      - "48501:8000"
    depends_on:
      - postgres

  postgres:
    container_name: horizont-center-postgres
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=#{DB_PASSWORD}#
      - POSTGRES_USER=caregivers
      - POSTGRES_DB=caregivers
    ports:
      - 5432
    volumes:
      - ".:/var/lib/postgresql/data:rw"

  nextjs:
    image: codeforacause/website-horizont-center:nextjs-#{TAG_NUMBER}#
    container_name: horizont-center-frontend
    ports:
      - 48500:3000
    environment:
      - BASE_URL=http://localhost:3000
      - API_URL=http://localhost:3000
      - STATIC_DIR=/
      - NAME=Negovatelji
      - TITLE=Negovatelji.com
      - DESCRIPTION=Negovatelji sajt opis sajta
      - SLOGAN=Negovatelji slogan koji ce da ima
      - ADDRESS=Negovatelji adresa
      - REGION=Negovatelji region
      - PHONE=+199999999
      - IMAGE=xconnect.jpg
      - AUTHOR=@thestartup
      - FACEBOOK_URL=https://negovatelji.com
      - TWITTER_URL=https://negovatelji.com
      - INSTAGRAM_URL=https://negovatelji.com
      - LINKEDIN_URL=https://negovatelji.com
      - COUNTRY=RS
      - POSTAL_CODE=21000
      - LOCALE=sr_Latn_RS
      - AUTH_STORAGE_KEY=g-profile
      - PROFILE_PAGE_SIZE=3
