version: '3.7'

services:

  django:
    image: codeforacause/website-horizont-center:backend-#{TAG_NUMBER}#
    container_name: horizont-center-backend
    environment:
      - APP_ENV=development
      - DB_NAME=caregivers
      - DB_USERNAME=caregivers
      - DB_PASSWORD=#{DB_PASSWORD}#
      - DB_HOSTNAME=postgres
      - DJANGO_PORT=8000
      - DJANGO_SUPERUSER_EMAIL=#{DJANGO_EMAIL}#
      - DJANGO_SUPERUSER_PASSWORD=#{DJANGO_PASSWORD}#
      - EMAIL_HOST_USER=#{EMAIL_HOST_USER}#
      - EMAIL_HOST_PASSWORD=#{EMAIL_HOST_PASSWORD}#
      - CORS_ALLOWED_ORIGIN=https://horizont.codeforacause.rs
      - ALLOWED_HOST=api.horizont.codeforacause.rs
      - CSRF_TRUSTED_ORIGIN=https://api.horizont.codeforacause.rs
    volumes:
      - ".:/var/lib/horizont-data:rw"
    ports:
      - "48501:8000"
    depends_on:
      - postgres

  postgres:
    container_name: horizont-center-postgres
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=#{DB_PASSWORD}#
      - POSTGRES_USER=caregivers
      - POSTGRES_DB=caregivers
    ports:
      - "5432"
    volumes:
      - ".:/var/lib/postgresql/horizont-data:rw"

  nextjs:
    image: codeforacause/website-horizont-center:nextjs-#{TAG_NUMBER}#
    container_name: horizont-center-frontend
    ports:
      - "48500:3000"
    environment:
      - BASE_URL=https://horizont.codeforacause.rs
      - API_URL=https://api.horizont.codeforacause.rs/api/v1
      - STATIC_DIR=/
